### ISSUE TITLE
Improve eureka registration times [Eureka]

### ISSUE THREAD

**Issue by spolnik** [spolnik/JAlgoArena#22]
improve eureka registration times for all services - for now it's too long

**Comment by nwoodthorpe-test1** [comment]
ו̸̙͓̙̝̯̥̗̩̟͈̗̠͐̏ͯ̒̈́̌̿̍̊̿͊̓ͯ̽̈ה̌̿ͩ̽̑͗ͮ̐͞҉̹͈̭̞̫̘͇̱̦̦͍̱́ע̭͈̱̣̤͕͙̹̙̮̲̝ͪͤ͐̿͂ͥ͌ͦͮͪ̕͢͠ב̨͍̹̠̜͙͙̺̝̬̙̯̹͚͊̈̉͌ͥ̈́̇͜ר̵̲̭̘̭̌́̐̚י̨̹̹͔̫̺̳͙̒ͣ̉̾̀̾͗͂̑͐̈̄̃̏̃̃͂͘͜͟ת̸̴̶̨͈̤̘͎̘̫̪̺̱̅͒̓̋͐ͣ ̧̻̤̮̠͛̍ͣ͊́̕͡͡ה̵̸̶̷̧̣͕̘̪̱̘̗̯͍̮͗̑ͫ̓ͧ̿̀ͪ͛̎ͦ̈́ͩו̉̆̈́͋̄ͫ̀̄͋̂͑̽̓̋͐̎̕͘҉̴͎̮̝̥̼͈̝̠̹̤͓̭̗́ק͔̹̰̺͙̔̓͗ͣͦͨ̔̒̇̈́ͪ̅̏͡͡͡͞ל̴̞̳̩̞̻̼͚̜͔͉̮̺̜̩͚̓ͮ̀̌̈́͘ד̴͉͔̗̬͔̑̉̏͌ͯ͜͟ͅͅ ̸̴̺̺͕̗̦̙͇̟̽͐̔̔ͦ͊ͯ̑ͧͪͥ͆ש͗̈ͬͭ̐͏̢̞̻͚̗̖̖̮͔͓͍͖͙̹̗͈͍̠̳͝נ̨̡̰̜͖̰͙̪̺ͫͪ̑̍̎ͯ̿ͣ͒ͥ͊̌͂ͭ̃̐͌̚͜י̵̵̼̙̺͚͓͍̲̝̹̥͍͉̦̻ͥͭ͗ͪ͛̃̄̀͞ו̧̳̙͙̃ͬͭ̓̉̊̾̃ͥ̏͛ͪ̆̊̌͑̽̍͡ה̴̵̨̥͓͖̟͎̞̖ͭ͗͋ͥ̏ͥͮ̆ͭ͝ע̶̶̡̨͉͉̯̲͖͔̠̞͚̺͔͇̪̤̺̻͇̈̈́̋͒͋ͫͦ́̒ͭ͛̽̈̋̓͘ב̛͌̇͋ͪ̽ͮ̉̀ͫ̄̓̋͗̐̆ͣ̃͝͠͠͏̭͎͙̳̫̹̲͖̰̹͔̜̟̭͕̪ר͉̼̘̯̭̙͉̭̬̫̞̗̗̭̯̒ͧͫ͊̾͋̅͗͑̀ͨ͡͠י̡̩̩̟̮̱̍̎̔̔͆̄̅̔̿̒͛͊̉̇̃̆̋̚͘͞ת̽̑͂̊ͭ̀ͦͮ̀ͯ͏̡̫̰͈̭̳͕̣͚̕ ̶̡̦͈̦͎̤̭̤̣̥̋ͥ̽ͬ̿͐̂̉̉͐̔ͪ̇ͧͦ̈́̀ה͑ͦ͐ͤ̑̄͑̓͒ͧͧ͠҉̬͍̣̱̯̬ו̢͕̲̼̠̘̊ͭ́̾̏̈́͘͠͠͡ק̷͍̥̼̳̖̥̦̻̞̦̺̤̠̥͚̥̓̂̐ͨ̚͘͟͠ל̧ͣ͊͆ͦ̓͂ͥ͋͌̄́̓̇̔̆ͦ̊҉̨̮̰̩͙̫̟̰̖̝̺͜ד̷̵̅̿̾͑̊̉͊̈́͞͏̵̰̬̯͍͈͕͎͕̥̥̭ͅ ̜͔̰̭̹͎̪̭͑ͨ̔̈ͨͧ̎̇̋̄ͬ͆̚͢͠ͅש̟̮̗͈̤̜̩͇͓̩̬̈́͒̌̔̔̆̀̚̕͜͝נ̵̴̴͕̳͖̱̪͛ͣͫ̎ͫ̊͒י̵̡͙̯̫͓̹̼̥̥̹̺ͣͭͭͣͥ̂̀͜͞ו̷̨̛̲̹̥͎̗͉͉̘̙̳̬̺̆ͯͣͯ͊̓̈́̑͗̒̅̚ͅה̸̧̘͖͔̻̬ͤ̀͆͂͐ͯ͋͟͠͝ע̢̛͓̱̳͓̐̅̐ͦ͗̓̔͊͂́ͪ̽̾ͪ̃ͮͬ́͘͝ב̢̠̮̦̭̖̤̦̳̲͈͓̈ͯ̄̆ͦ̿ͨ̍̌ͦͬ͐͑ͪ͑ͥ̏̇͜ר̶̸̧̹͇̖̭͖̪̳͈͉̩̤͈̌̑̏̌͋̉̀͝ͅי̷̡̢̧̤̱̗̹͉̭͈̲̳̦͇̰̳͓͚̙̰́̽ͣ̍ͭͧ̍ͦ̈͗̅̽͊̆ͬ̀ͫ̕ת̒̀ͧ̑̔̌̓ͫͩ̚҉̸̡̱̞̤̝̗͈̰ ̷͇̝̤͚̥͈̩͔͔̬͙̱͚͙͓͖̺͈̄͌͂̒́͛ͪ̀́̕͟ה̸̖̗̺̳̝͉̠̥̳͍̮̣͎͇͇͎͈̱͚͑̋ͫ̈ͩ̍̃ͨ̆͆ͣ̀͟͝ו̢̖̺̬̙̺̲͙͇̮̾͆ͨ̅̉̅́ק̡̢̤̬̰̪̬ͮͮ̿̄͂͛ͤͦ̏̃̂ͩ͘͝ל̵̨͖̝͚̙̙̼͔̤̥ͨ̅͌͗̅͂̇͘͞ד̧͇͇̘̘̙̯̲̩̘̠̘͉̣̘̞̞̺̻͊́ͦ͌̐ͤ͗̀̾͂̀̾̑ͨ͞ͅ ̬̦̹̠͖̥̠̰̙̝̼̫̺͕̝̗͉ͫͥ́͗͐ͮ͌̔ͦ̅̂͡͠ש̶̠͉͙̤͎͉͖͕̙̦͙̺͔̘ͧ̍̇ͨ̋ͭ͛ͬ̾ͬ͢נ̡͇̩̫̻̩͍̰̻̼͈͍̲̥̹̖̄͒̓ͭ̀͟ͅי̡̢̝͚̘̝͚͔̹̖̪̙̖͍̎̌͒̂ͧͭ̊̂͊͘͝ͅו̸̴̮̥̜̮̦̟͔͕̰̗̻͓̮̙̗̀ͬ̓ͦͬ̽̿̾ͫ͐̅ͩ̑̒̑̒̏̚͟͢͠ה̷̛̟͖̤̗̮͓̮͈̺̜̺̱̂͊ͨ͒̂̃ͣͫ́͂̔́ͭ͑̓̈̚ע̢̤̫̟̻͎̤ͥͦ͐͆ͯ̾̉̄͜ב̻̮̟̦̱̯̘͉̰̹͖̜̞ͣ͗̽͆͑ͬͬ̓̄̋͌̅̊́̈͋̚̕͞ר̉̊̉̅́ͫ̈́͂̐ͮ̇̾͛ͦ̓̊͏҉̻̰̪͎͔̹̗̝̰̫̣̥̱̟̮̩͢͠י̸̢̩̳̼̫͈̳̫͖̘̯̳͖̫̣̺̰ͮ̎̈́ͬ̓̌̇ͦͦͫ͋̓̄̕͘ͅͅͅתͯ̔̊̒ͥͮ̽ͯ̀́̿̂͊̀̃̐ͦ̚͏̴̟̭̼̞̰̭̘̲̥̙͖̗̩̭͉̪̪͕͖͘͠ ̶̨̮͉̮̼̦̩̱͎͙̳̙͈͚̝̜͖̻ͧ̑̑͐̃ͥͩͬ̄ה̡̧͈͉͈̰͉͈̳̣̫̻̰̝͖͐ͦͬͩ̆̆ͣ̓̾̚̚͝ͅו͚̫͈͖͕̫͚͖͙̺̎̿ͩ̔̂̿̂̒ͩ̋͒̀ק̠͍͖̬͕̫͎͇̘̯̬͎̗̥̞͎͎̺ͯͩ͋̅̊͗́̍͋̀̕̕͡͝ל̩̳̤̼̘̱͕͓͈͓̓͂͂̒ͫ͌ͩ̆̋̇̃̓̀́̚͞ד̴̵͚̗͇̲̝̠̦̓͂̌͐̎ͯ̉̏̉ͫ̆̉̈̓̇͡ ̴̺̻̪̹̣̰̆͑̌̆̓ͬ͗ͧ̉̎̀̇̋ͮ̌̽̅͟͞ͅש̃ͤ͊̆̑̆̌̆ͨ̾ͤ̌̽̿̊͏̖̯̘̥̭̞̠͕͍̻̬̠̜͚̬̫̯̤͘נ̶̢̼̜͓̭͓̤͇̝̲̰̬̙̳͆͒ͩ̇ͮͅי̵̗͉̫̝̝̘̱̟̿͐́̒̌͒̃̄ͧ̈ͫ͒̋̂̓͌͊̈̀͘̕̕ו̶̡̣̲̺̭̱͖̻̙̲̱̱̹ͥ͋̍̓͑ͩ̀̏̐ͭ͋̅ͥ̌ͧ̊̚̚ה̡̨̳̰̖̮͍̟̐͋̓͊̾̍ͥ́ͅע̵̖͔̱̻̼̞̻͉̦ͧ̉̀̀ͣ̊͌̈ͥ́̑͊̊͆̑͗͗͘͡ͅב̴̴̼̖͚̹̯̤̙̹͚͈̽͒ͦ̎̐̓̋ͤͮ͊͌̿͂͆̂̓͘͡ͅר͍͚̺̩̱̩̠͇͓̜ͥ̐̍̐͘י̶̲̱̣̟̳͔͚̙͙̮ͨ̈̌̎̂͒̍̓ͥͮ̾ת̷͉̮͍̥͍̰̮ͣ͊ͪ̿̾̽͊̄ͣ̇͘͠ ̴̞̼̟̤̹̙̻͚͚͚̲̭̱͚͛̌́̐ͫ̑̄ͧ̍͟͢ͅͅה̸̛̞͉͍̼̳̝̼̪̦̅̋ͯ͌̆ͦͥ̐ͥ͑ͪͦ̈ͩ̇ͦ͊̚͘͠͞ו̧̧̛̛̜̜͙̯̤͇͉͖͛͒͑͠ק̽ͬ̍̽ͨ͊͌ͦ͏͏͇̟̱͍̱̝̬̖̟͈̖ͅ
